### PR TITLE
Modernize CMake include and linking resolution.

### PR DESCRIPTION
**Pull request by FunMiles**
In modern CMake, `TARGET_LINK_LIBRARIES(executable libA::libA)` will correctly set the required include path and compilation flags. It also correctly does add the transitive dependencies. This resolve issues such as https://github.com/systemed/tilemaker/issues/502 and https://github.com/systemed/tilemaker/issues/536.

It does require that `libA` is also modernly made for CMake.  For most libraries for which a CMake distribution provides a FINDLibrary.cmake, this will be the case. Lua is unfortunately an exception.
For other libraries, one can add an imported target to use this approach. 

Currently only tested on mac.

### CODE REVIEW

**Comment by systemed** [comment]
Looks great - thank you!

The CI is failing on the Windows build - any ideas?

**Comment by FunMiles** [comment]
> The CI is failing on the Windows build - any ideas?

Unfortunately, I do not currently have access to Windows, and when I do, I am rather ignorant of its quirks. However in this case, I think I have found the issue. MSVC uses another version of SQLite3 than the rest of the gang. Hopefully my followup commit fixes the issue.

Is there a way I can run the CI on my fork before pushing new changes to the PR?

**Comment by FunMiles** [comment]
Success! However I am going to make one more change to slightly simplify the handling of the two cases.

**Comment by systemed** [comment]
Superb! Thank you.

**Comment by systemed** [comment]
Bizarrely, although it ran ok on the PR, when merged it's now failing on the docker build:

````
CMake Error at //CMakeLists.txt:36 (find_package): 
Could not find a package configuration file provided by "Protobuf" with any
of the following names:

     ProtobufConfig.cmake
     protobuf-config.cmake

Add the installation prefix of "Protobuf" to CMAKE_PREFIX_PATH or set
"Protobuf_DIR" to a directory containing one of the above files.  If
"Protobuf" provides a separate development package or SDK, be sure it has
been installed.
````

https://github.com/systemed/tilemaker/actions/runs/6598962033/job/17927614211

**Comment by systemed** [comment]
This is now fixed and the Docker build is working again.

**Pull request merged**
