### PR TITLE
Pack OutputObject bitfields more efficiently

### PR DESCRIPTION
**Pull request by systemed**
Restricting `objectID` to 40 bits as per #293 means we can fit the rest of the flags into the remaining 24 bits.

Edit: this works fine on clang, but GCC appears to squawk at the bitfield not being big enough for the uint8_t underlying the enum, even though we only have 2 bits worth of enum values.

Edit 2: we may need to look at newWayID/MAX_WAY_ID too.

### CODE REVIEW

**Comment by kleunen** [comment]
Change the 'enum class' to an 'enum' and just store in an 'uint8_t : 2' in the outputobject. You lose the type checking, but ok ..

**Review by kleunen — COMMENTED** [review]
OUTPUTGEOMETRY_POINT, OUTPUTGEOMETRY_LINESTRING, OUTPUTGEOMETRY_POLYGON ?

Or:

OG_POINT, OG_LINESTRING, OG_POLYGON

Or:

GEOMETRY_POINT, GEOMETRY_LINESTRING, GEOMETRY_POLYGON 

:)

**Comment by systemed** [comment]
I did wonder about GEOMTYPE_POINT but I'm a lazy typist ;)

**Comment by kleunen** [comment]
I think at the moment you are not actually saving any bytes on the outputobject. Because the reference count (uint32_t) was combined with the flags before. And now, reference count is still uint32_t, but is stored aligned on 64bit alignment (uint64_t).

**Comment by systemed** [comment]
Gah, yes, you're right. 40 bytes each time.

I'm not sure if it would be possible to replace AttributeStoreRef with an intrusive_ptr and a reference count in the spare four bytes... sounds slightly plausible but it's way beyond my C++-fu :)

**Comment by kleunen** [comment]
Maybe enable packing on the struct. 
pragma pack

I can look it up later

**Comment by kleunen** [comment]
Or replace attributestoreref with an 32 bit attributestoreindex. Not sure if that is possible

**Comment by kleunen** [comment]
Try:

````C++
#pragma pack(push, 4)
struct OutputObject {
...
}
#pragma pack(pop)

**Comment by systemed** [comment]
That works - we're down to 36 bytes (from 40) with that.

**Comment by kleunen** [comment]
Another possibility to further reduce the OutputObject size is to have a list of OutputObjects (vector), and make the references in the tile-index non-owning references (in other words: OutputObject *). That way, you can remove reference count.

**Comment by kleunen** [comment]
See #307, it removes the reference count

**Comment by kleunen** [comment]
Another optimization would be to store the osmID with the generated geometry in the osm_store. That way, you do not need the handle in the outputobject. But you would lookup the geometry using the osmID.

**Comment by kleunen** [comment]
#307 now includes also the optimization to use the OsmID to lookup the generated geometry in osmstore instead of storing a handle/pointer. OsmID should be 42 bits now: 40 bits id + 2 bits type: from shape, node, way or relation.

**Comment by systemed** [comment]
Excellent - I’m away at the moment but look forward to playing with this when I’m back.

**Comment by kleunen** [comment]
I rebased PR #307 onto this PR. Moreover, with an additional optimization to the attribute store reference, i have the size of the outputobject now down to 16 bytes.

**Comment by systemed** [comment]
That’s amazing!

**Comment by systemed** [comment]
Superseded by #307.

**Pull request closed without merging**
