### PR TITLE
C++ tileserver

### PR DESCRIPTION
**Pull request by systemed**
This is #301 brought up-to-date and with a couple of extra command-line options. It should help alleviate the pain-point people have if they don't already have Ruby up and running on their system.

### CODE REVIEW

**Comment by pnorman** [comment]
Another option is Martin (including via docker), so we'd be looking at users who don't have ruby running or docker running.

**Comment by systemed** [comment]
Indeed, and there are PHP equivalents and so on. The purpose of this is a “don’t make me think” way of quickly testing out your tilemaker-produced vector tiles, without having to identify and install an additional solution. For production I am sure people will continue to use one of the more fully featured servers available.

**Comment by systemed** [comment]
Thanks again @bdon and sorry it's taken so long to merge this!

**Comment by bdon** [comment]
Thanks for the update! Good to have more serving options... :P

**Pull request merged**
