### PR TITLE
Parallel loading of osm.pbf file

### PR DESCRIPTION
**Pull request by kleunen**
This PR performs parallel loading of the osm.pbf file. There is still a lot of locking going on, but it seems some level of parallel processing of the pbf file is possible. Have a try to see how it works. 

I removed the index building in this PR.

### CODE REVIEW

**Comment by systemed** [comment]
Cool!

So far it seems a little slower (39m47 on the GB extract vs 34m11) but as it's a WIP I won't take that as a final answer. :)

**Comment by kleunen** [comment]
You use the osm store or not? Maybe try without osm store

**Comment by kleunen** [comment]
I am suspecting that actually this lua interpreter is not multithreaded and locks when executing the script. So different scripts can not be executed in parallel.

**Comment by systemed** [comment]
That's a very good point - http://lua-users.org/wiki/ThreadsTutorial would seem to corroborate that.

I _think_ we could fix that by having a Lua state per thread, rather than one globally:

> Each thread in C which interacts with Lua will need its own Lua state. Each of these states has its own runtime stack. When a new C thread is started, you can create its Lua state in one of two ways.

**Comment by kleunen** [comment]
One way is to call lua_open. This creates a new state which is independent of the states in other threads. In this case, you'll need to initialize the Lua state (for example, loading libraries) as if it was the state of a new program. This approach eliminates the need for mutex locks (discussed below), but will keep the threads from sharing global data.

**Comment by kleunen** [comment]
Have another try, 

also check the number of generated points/lines/polygons. 
I think maybe some lines are missing now ? Not completely sure

**Comment by systemed** [comment]
I’m away for a few days (probably not too feasible to run tilemaker on my phone ;) ) but I’ll have a look when I’m back home.

**Comment by kleunen** [comment]
No problem. The mmap allocator is still preventing it from really scaling up. So. No big improvements yet.

i just wondered why i see a much lower number of linestrings stored. I store the generated geometries now based on osmID. Is it possible the same linestring is generated to different output objects with different attributes? Maybe at different zoom levels?

**Comment by kleunen** [comment]
It works now to some extend. The filesystem backed --store does not work, it crashed. Only the shared memory. But it seems there is some degree of parallel loading now.

**Comment by kleunen** [comment]
Small error in this store code, it is fixed now

**Comment by kleunen** [comment]
On my 12 core machine it nows reads the great britain extract in 3 and and half minute or so and generate the geometries. The ways are most benefiting from parallel reading.

**Comment by kleunen** [comment]
IO is really becoming a bottleneck now. When I do this conversion on my laptop, 12 cores, I see the processing sometimes writing at 1000M/sec - 1200M/sec. It is writing data to store like crazy.

**Comment by kleunen** [comment]
I made some small fixes, but I do notice there are still more polygons generated than before these commits: 

Now (bretagne):
Stored 29831824 nodes, 3956027 ways, 6696 relations
Shape points: 0, lines: 0, polygons: 42
Generated points: 632362, lines: 1232032, polygons: **3189473**

Before:
Stored 29831824 nodes, 3956027 ways, 6696 relations
Shape points: 0, lines: 0, polygons: 42
Generated points: 632362, lines: 1232032, polygons: **3189464**

**Comment by kleunen** [comment]
It is really fast now, even on my small 4 core mobile cpu, reading 4 threads alomst 100% at the same time. The number of generated geometries (lines/polygons) is different than before this commit. I have no idea where this difference is coming from. The result is always the same, independent of how many threads are used. So i guess it is not a threading issue.

**Comment by systemed** [comment]
````
real	24m49.112s
user	323m10.144s
sys	2m28.737s
````

👍 

That's a huge improvement. I'll look further tomorrow (only just got back) but that's a good 10 minutes faster than previously.

**Comment by kleunen** [comment]
Compare also the number of generated geometries. Also look at what the cpu usage is at loading. On my 12 core laptop it is about 90%

**Comment by kleunen** [comment]
Ah ok, i do see a crash on windows executable when reading the relations of my netherlands extract. I have no idea where this is coming from. 

I am running now using a sanitizer, and i did found two other issues. But not the crash yet. It is quite slow now, so I am just leaving it running.

**Comment by kleunen** [comment]
I think i found the crash issue also

**Comment by systemed** [comment]
It looks like all 16 CPUs in use. Memory usage 17.6GB max. Results:

````
Stored 139385816 nodes, 19111319 ways, 65265 relations 
Shape points: 0, lines: 0, polygons: 678
Generated points: 3846401, lines: 11445263, polygons: 10712264
Zoom level 7, writing tile 1060956 of 1060956                
Filled the tileset with good things at ../tm_debug/gb_parallel.mbtiles

real	24m39.443s
user	314m3.797s
sys	2m19.267s

-rw-r--r-- 1 richard richard 1266479104 Jun  2 21:14 ../tm_debug/gb_parallel.mbtiles
````

Compared to master (15.2GB max):

````
Stored 139385817 nodes, 19111319 ways, 65265 relations
Shape points: 0, lines: 0, polygons: 678
Generated points: 3846401, lines: 11445266, polygons: 10712232
Zoom level 14, writing tile 1060956 of 1060956               
Filled the tileset with good things at ../tm_debug/gb.mbtiles

real	34m20.678s
user	311m0.885s
sys	1m38.623s

-rw-r--r-- 1 richard richard 1328132096 Jun  2 23:27 ../tm_debug/gb.mbtiles
````

So it's much faster; there's an increase in RAM used (probably because I was running with `--compact` on master); there's a very slight difference in the number of polygons (which I don't think is significant), and the generated file is a little smaller. I'll eyeball the resulting tiles to see if I can spot any differences.

**Comment by kleunen** [comment]
In your case there is one node less stored. That is a just silly. Where is this one single node. :)

**Comment by kleunen** [comment]
There should also be no reason why the output is smaller. So have a good look at the map. See if there are any differences.

**Comment by kleunen** [comment]
When I look at my netherlands extract: 
Stored 191051541 nodes, 28247961 ways, 106013 relations
Shape points: 0, lines: 0, polygons: 168
Generated points: 15160547, lines: 8783910, polygons: 22598060

And osmium fileinfo:
  Number of nodes: 191051541
  Number of ways: 28247961
  Number of relations: 302886

Some of the relations are not stored.

**Comment by systemed** [comment]
Indeed - we wouldn't expect tilemaker to store all the relations because we don't parse them all (routes, for example). We only store all the ways because they might be used by the relations (and all the nodes because they might be used by the ways).

I ran Europe with this PR overnight. 54GB max memory usage (using store on SSD, obviously) and pretty quick:

IMG_3021

We seem to be closing linestrings when we shouldn't. I think this might be related to simplifying - it only seems to affect geometries that are simplified at the given zoom level.

Screenshot 2021-06-03 at 09 27 47

Screenshot 2021-06-03 at 09 27 07

**Comment by kleunen** [comment]
It might be simplifier, but it might also be the combining. Similar issue was this issue:
https://github.com/systemed/tilemaker/issues/240

**Comment by kleunen** [comment]
Oh wait, i think i know what the issue might be

**Comment by systemed** [comment]
That fixed it!

**Comment by kleunen** [comment]
There is still at least one thing i want to change. So dont merge yet.

**Comment by kleunen** [comment]
Made some more small changes to clean up and improve some small things.

**Comment by systemed** [comment]
Europe with the latest version of this PR:

IMG_3027

Looks good to me! Ready to merge?

**Comment by toshelp** [comment]
It is a rendering result of Sweden, but it seems that some "wood" is lost.
Have any plans to fix this?

coordinate ```7.8/60.123/16.572``` 
sd

**Comment by kleunen** [comment]
> It is a rendering result of Sweden, but it seems that some "wood" is lost.
> Have any plans to fix this?
> 
> coordinate `7.8/60.123/16.572`
> sd

Is the result of this PR or PR 239 ? 
````
diff --git a/include/osm_lua_processing.h b/include/osm_lua_processing.h
index 5911f66..8c1cfa9 100644
--- a/include/osm_lua_processing.h
+++ b/include/osm_lua_processing.h
@@ -125,7 +125,7 @@ public:
         } else if (isWay && !geom::is_valid(geom,failure)) {
             if (verbose) std::cout << "Way " << originalOsmID << " has " << boost_validity_error(failure) << std::endl;
         }
-        if (failure==boost::geometry::failure_self_intersections || failure == boost::geometry::failure_few_points) 
+        if (failure == boost::geometry::failure_few_points) 
                        return false;
                if (failure==boost::geometry::failure_spikes)
                        geom::remove_spikes(geom);

**Comment by toshelp** [comment]
This is the result of this PR.
Wood is not lost in the current master branch.

**Comment by kleunen** [comment]
Hmm, yes, there is something changed which indeed causes certain polygons to go missing. It would be be good to resolve this.

**Comment by kleunen** [comment]
I do see that this init:
https://github.com/systemed/tilemaker/blob/master/src/osm_lua_processing.cpp#L500

Is not performed in setRelation:
https://github.com/systemed/tilemaker/blob/master/src/osm_lua_processing.cpp#L580-L585

**Comment by systemed** [comment]
Not sure - do you have an OSM object ID and a (preferably small :) ) extract where this is consistently happening?

**Comment by kleunen** [comment]
@toshelp Has this island on the right which has a large area of forest is missing. Let me make an extract of this.

**Comment by kleunen** [comment]
[Sweden extract](https://mqtt.kleunen.nl/map/sweden-extract.osm.pbf)

image

**Comment by kleunen** [comment]
https://www.openstreetmap.org/way/34905544#map=12/60.3996/18.4346

**Comment by kleunen** [comment]
It seems the geometry does get created, polygon with 227 nodes, and it is processing in the tile generation phase

**Comment by systemed** [comment]
Found it!

When we call `SetMinZoomByArea` in the Lua script, and that in turn calls `way:Area()`, it's receiving a negative area - -25135521.103994 to be precise.

This causes `SetMinZoomByArea` to write it out with a `minZoom` of 14, so the polygon isn't visible at any lower zoom level.

The [Boost.Geometry docs](https://www.boost.org/doc/libs/1_61_0/libs/geometry/doc/html/geometry/reference/algorithms/area/area_1.html) say that a negative area indicates "Reversed polygon (coordinates not according their orientiation)".

So this suggests that we need to correct the orientation of the polygon before the Lua script gets hold of it (or on the first call to `:Area()`).

**Comment by kleunen** [comment]
Aha. I removed a correct call from the osm store. But the correctgeometry should correct the orientation also right? Or note?

**Comment by kleunen** [comment]
Ah wait. This is not before calling the lua script

**Comment by systemed** [comment]
`:Area()` uses polygonCached, whereas `:Layer()` takes linestringCached, assigns the points to mp, and then corrects _that_. So the original polygonCached is never corrected, even though we'd typically be calling `:Area()` after `:Layer()`.

**Comment by kleunen** [comment]
But then I guess it is best to immediatly call CorrectGeometry in the Cached functions ? 
That way it is always correct when it is used

**Comment by systemed** [comment]
That would make sense!

**Comment by kleunen** [comment]
If i do that it looks completely distorted: 
image

Not sure what is happening there

**Comment by kleunen** [comment]
I will just restore the correct like it was on the current master:
https://github.com/systemed/tilemaker/blob/master/include/osm_store.h#L584

**Comment by kleunen** [comment]
This works fine, so maybe some other time have a good look at this geometry correction :)

**Comment by systemed** [comment]
Excellent.

@toshelp, does this fix things for you?

**Comment by toshelp** [comment]
That's fixed!
Thank you.

**Comment by kleunen** [comment]
cheers

**Comment by systemed** [comment]
Yay!

Thanks again - massive improvement in performance.

I'll update the docs at some point - I slightly miss `--compact` mode but there's probably not much practical difference if people are using an on-SSD store.

**Comment by kleunen** [comment]
It wouldn't be too difficult to readd the compact mode. But it indeed only provides benefit if using the in-memory converter. But i went through the OSMStore and decided to keep the code base as simple as possible. All these option accumulating also makes it difficult to maintain.

**Comment by systemed** [comment]
Yep, I can understand that. Let's leave it out for now and if anyone has an issue I'm sure they'll say so!

**Pull request merged**
