### PR TITLE
Tile generation use blocks of 100 tiles per worker

### PR DESCRIPTION
**Pull request by kleunen**
Generate blocks of 100 tiles per thread pool worker. This reduces memory consumption a bit on large areas and improves the tile progress output.

### CODE REVIEW

**Comment by systemed** [comment]
Looks good! I haven't timed it yet but it seems a little faster.

I get slightly weird progress output at the end:

    Zoom level 4256283078, writing tile 1890 of 1990               

followed by

    Zoom level 12, writing tile 1990 of 1990

which seems odd as it should finish at z14 (not 4256283078 :) ).

**Comment by kleunen** [comment]
That is strange

**Comment by kleunen** [comment]
It is possible the zoom level sometimes jumps back. Because tiles from higher zoom level may finish later. But the value you mentioned looks corrupted

**Comment by kleunen** [comment]
It was accessing end_index, while last element is (end_index - 1)

**Comment by systemed** [comment]
That seems happier! Thank you.

**Pull request merged**
