### PR TITLE
Fix some things in PR 239

### PR DESCRIPTION
**Pull request by kleunen**
Simplify fix out-of bounds access
Virtual destructor missing
Don't drop polygon if self-intersecting

### CODE REVIEW

**Comment by systemed** [comment]
I guess the simplify and self-intersecting changes are already fixed but we still need the virtual destructor fix?

**Comment by kleunen** [comment]
No, because the whole virtual and PbfReaderOutput is removed now in the master. It is using OsmLuaProcessing directly.

**Comment by systemed** [comment]
Ah, hmm. I'm still getting very intermittent segfaults, not sure why.

**Comment by kleunen** [comment]
Hmm, i hope not a threading issue. Maybe run with thread sanitizer:
https://github.com/google/sanitizers/wiki/ThreadSanitizerCppManual

**Comment by systemed** [comment]
It seems to be close to the end of the entire process rather than on .pbf read. I'll keep an eye out and see if it happens again. Will close this for now.

**Pull request closed without merging**
