### PR TITLE
 Tilemaker CI for windows, macos and linux with boost

### PR DESCRIPTION
**Pull request by kleunen**
CI for windows, linux and macos
- Build boost from CI, this is required because boost is removed from virtual environments
- Lua 5.4 fixes
- LuaJit compilation
- Artifacts for windows/linux/macos are generated

First build is slow(boost is build), but the dependencies are cached.

### CODE REVIEW

**Comment by systemed** [comment]
This looks good!

I get a build issue with the latest macOS (Big Sur) - though I think the current master won't build with that either (previously I'd been testing on 10.14). Helpful C++ error message below:

<details>
<summary>Click for error</summary>

````
[  4%] Building CXX object CMakeFiles/tilemaker.dir/src/osm_lua_processing.cpp.o
In file included from /Users/richard/Code/C++/tilemaker/src/osm_lua_processing.cpp:1:
In file included from /Users/richard/Code/C++/tilemaker/include/osm_lua_processing.h:10:
In file included from /Users/richard/Code/C++/tilemaker/include/osm_store.h:21:
In file included from /usr/local/include/boost/unordered_map.hpp:17:
In file included from /usr/local/include/boost/unordered/unordered_map.hpp:21:
In file included from /usr/local/include/boost/unordered/detail/map.hpp:6:
/usr/local/include/boost/unordered/detail/implementation.hpp:1813:32: error: no matching constructor for initialization of 'std::__1::pair<const unsigned long long,
      std::__1::pair<VarIntVector<unsigned long long, boost::container::scoped_allocator_adaptor<boost::interprocess::node_allocator<unsigned char, boost::interprocess::segment_manager<char,
      boost::interprocess::rbtree_best_fit<boost::interprocess::mutex_family, boost::interprocess::offset_ptr<void, long, unsigned long, 0>, 0>, iset_index>, 64> > >, VarIntVector<unsigned long
      long, boost::container::scoped_allocator_adaptor<boost::interprocess::node_allocator<unsigned char, boost::interprocess::segment_manager<char,
      boost::interprocess::rbtree_best_fit<boost::interprocess::mutex_family, boost::interprocess::offset_ptr<void, long, unsigned long, 0>, 0>, iset_index>, 64> > > > >'
          new ((void*)address) T(boost::forward<Args>(args)...);
                               ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/include/boost/unordered/detail/implementation.hpp:2040:11: note: in instantiation of function template specialization
      'boost::unordered::detail::func::construct_from_args<boost::container::scoped_allocator_adaptor<boost::interprocess::node_allocator<boost::unordered::detail::node<boost::container::scoped_allocator_adaptor<boost::interprocess::node_allocator<std::__1::pair<unsigned
      long long, std::__1::pair<VarIntVector<unsigned long long, boost::container::scoped_allocator_adaptor<boost::interprocess::node_allocator<unsigned char,
      boost::interprocess::segment_manager<char, boost::interprocess::rbtree_best_fit<boost::interprocess::mutex_family, boost::interprocess::offset_ptr<void, long, unsigned long, 0>, 0>,
      iset_index>, 64> > >, VarIntVector<unsigned long long, boost::container::scoped_allocator_adaptor<boost::interprocess::node_allocator<unsigned char,
      boost::interprocess::segment_manager<char, boost::interprocess::rbtree_best_fit<boost::interprocess::mutex_family, boost::interprocess::offset_ptr<void, long, unsigned long, 0>, 0>,
      iset_index>, 64> > > > >, boost::interprocess::segment_manager<char, boost::interprocess::rbtree_best_fit<boost::interprocess::mutex_family, boost::interprocess::offset_ptr<void, long,
      unsigned long, 0>, 0>, iset_index>, 64> >, std::__1::pair<const unsigned long long, std::__1::pair<VarIntVector<unsigned long long,
      boost::container::scoped_allocator_adaptor<boost::interprocess::node_allocator<unsigned char, boost::interprocess::segment_manager<char,
      boost::interprocess::rbtree_best_fit<boost::interprocess::mutex_family, boost::interprocess::offset_ptr<void, long, unsigned long, 0>, 0>, iset_index>, 64> > >, VarIntVector<unsigned long
      long, boost::container::scoped_allocator_adaptor<boost::interprocess::node_allocator<unsigned char, boost::interprocess::segment_manager<char,
      boost::interprocess::rbtree_best_fit<boost::interprocess::mutex_family, boost::interprocess::offset_ptr<void, long, unsigned long, 0>, 0>, iset_index>, 64> > > > > >,
      boost::interprocess::segment_manager<char, boost::interprocess::rbtree_best_fit<boost::interprocess::mutex_family, boost::interprocess::offset_ptr<void, long, unsigned long, 0>, 0>,
      iset_index>, 64> >, std::__1::pair<const unsigned long long, std::__1::pair<VarIntVector<unsigned long long,
      boost::container::scoped_allocator_adaptor<boost::interprocess::node_allocator<unsigned char, boost::interprocess::segment_manager<char,
      boost::interprocess::rbtree_best_fit<boost::interprocess::mutex_family, boost::interprocess::offset_ptr<void, long, unsigned long, 0>, 0>, iset_index>, 64> > >, VarIntVector<unsigned long
      long, boost::container::scoped_allocator_adaptor<boost::interprocess::node_allocator<unsigned char, boost::interprocess::segment_manager<char,
      boost::interprocess::rbtree_best_fit<boost::interprocess::mutex_family, boost::interprocess::offset_ptr<void, long, unsigned long, 0>, 0>, iset_index>, 64> > > > >, unsigned long long &,
      VarIntVector<unsigned long long, boost::container::scoped_allocator_adaptor<boost::interprocess::node_allocator<unsigned char, boost::interprocess::segment_manager<char,
      boost::interprocess::rbtree_best_fit<boost::interprocess::mutex_family, boost::interprocess::offset_ptr<void, long, unsigned long, 0>, 0>, iset_index>, 64> > >, VarIntVector<unsigned long
      long, boost::container::scoped_allocator_adaptor<boost::interprocess::node_allocator<unsigned char, boost::interprocess::segment_manager<char,
      boost::interprocess::rbtree_best_fit<boost::interprocess::mutex_family, boost::interprocess::offset_ptr<void, long, unsigned long, 0>, 0>, iset_index>, 64> > > >' requested here
          construct_from_args(
          ^
/usr/local/include/boost/unordered/detail/implementation.hpp:3774:54: note: in instantiation of function template specialization
      'boost::unordered::detail::func::construct_node_from_args<boost::container::scoped_allocator_adaptor<boost::interprocess::node_allocator<boost::unordered::detail::node<boost::container::scoped_allocator_adaptor<boost::interprocess::node_allocator<std::__1::pair<unsigned
      long long, std::__1::pair<VarIntVector<unsigned long long, boost::container::scoped_allocator_adaptor<boost::interprocess::node_allocator<unsigned char,
      boost::interprocess::segment_manager<char, boost::interprocess::rbtree_best_fit<boost::interprocess::mutex_family, boost::interprocess::offset_ptr<void, long, unsigned long, 0>, 0>,
      iset_index>, 64> > >, VarIntVector<unsigned long long, boost::container::scoped_allocator_adaptor<boost::interprocess::node_allocator<unsigned char,
      boost::interprocess::segment_manager<char, boost::interprocess::rbtree_best_fit<boost::interprocess::mutex_family, boost::interprocess::offset_ptr<void, long, unsigned long, 0>, 0>,
      iset_index>, 64> > > > >, boost::interprocess::segment_manager<char, boost::interprocess::rbtree_best_fit<boost::interprocess::mutex_family, boost::interprocess::offset_ptr<void, long,
      unsigned long, 0>, 0>, iset_index>, 64> >, std::__1::pair<const unsigned long long, std::__1::pair<VarIntVector<unsigned long long,
      boost::container::scoped_allocator_adaptor<boost::interprocess::node_allocator<unsigned char, boost::interprocess::segment_manager<char,
      boost::interprocess::rbtree_best_fit<boost::interprocess::mutex_family, boost::interprocess::offset_ptr<void, long, unsigned long, 0>, 0>, iset_index>, 64> > >, VarIntVector<unsigned long
      long, boost::container::scoped_allocator_adaptor<boost::interprocess::node_allocator<unsigned char, boost::interprocess::segment_manager<char,
      boost::interprocess::rbtree_best_fit<boost::interprocess::mutex_family, boost::interprocess::offset_ptr<void, long, unsigned long, 0>, 0>, iset_index>, 64> > > > > >,
      boost::interprocess::segment_manager<char, boost::interprocess::rbtree_best_fit<boost::interprocess::mutex_family, boost::interprocess::offset_ptr<void, long, unsigned long, 0>, 0>,
      iset_index>, 64> >, unsigned long long &, VarIntVector<unsigned long long, boost::container::scoped_allocator_adaptor<boost::interprocess::node_allocator<unsigned char,
      boost::interprocess::segment_manager<char, boost::interprocess::rbtree_best_fit<boost::interprocess::mutex_family, boost::interprocess::offset_ptr<void, long, unsigned long, 0>, 0>,
      iset_index>, 64> > >, VarIntVector<unsigned long long, boost::container::scoped_allocator_adaptor<boost::interprocess::node_allocator<unsigned char,
      boost::interprocess::segment_manager<char, boost::interprocess::rbtree_best_fit<boost::interprocess::mutex_family, boost::interprocess::offset_ptr<void, long, unsigned long, 0>, 0>,
      iset_index>, 64> > > >' requested here
          node_tmp b(boost::unordered::detail::func::construct_node_from_args(
                                                     ^
/usr/local/include/boost/unordered/unordered_map.hpp:226:23: note: in instantiation of function template specialization
      'boost::unordered::detail::table<boost::unordered::detail::map<boost::container::scoped_allocator_adaptor<boost::interprocess::node_allocator<std::__1::pair<unsigned long long,
      std::__1::pair<VarIntVector<unsigned long long, boost::container::scoped_allocator_adaptor<boost::interprocess::node_allocator<unsigned char, boost::interprocess::segment_manager<char,
      boost::interprocess::rbtree_best_fit<boost::interprocess::mutex_family, boost::interprocess::offset_ptr<void, long, unsigned long, 0>, 0>, iset_index>, 64> > >, VarIntVector<unsigned long
      long, boost::container::scoped_allocator_adaptor<boost::interprocess::node_allocator<unsigned char, boost::interprocess::segment_manager<char,
      boost::interprocess::rbtree_best_fit<boost::interprocess::mutex_family, boost::interprocess::offset_ptr<void, long, unsigned long, 0>, 0>, iset_index>, 64> > > > >,
      boost::interprocess::segment_manager<char, boost::interprocess::rbtree_best_fit<boost::interprocess::mutex_family, boost::interprocess::offset_ptr<void, long, unsigned long, 0>, 0>,
      iset_index>, 64> >, unsigned long long, std::__1::pair<VarIntVector<unsigned long long, boost::container::scoped_allocator_adaptor<boost::interprocess::node_allocator<unsigned char,
      boost::interprocess::segment_manager<char, boost::interprocess::rbtree_best_fit<boost::interprocess::mutex_family, boost::interprocess::offset_ptr<void, long, unsigned long, 0>, 0>,
      iset_index>, 64> > >, VarIntVector<unsigned long long, boost::container::scoped_allocator_adaptor<boost::interprocess::node_allocator<unsigned char,
      boost::interprocess::segment_manager<char, boost::interprocess::rbtree_best_fit<boost::interprocess::mutex_family, boost::interprocess::offset_ptr<void, long, unsigned long, 0>, 0>,
      iset_index>, 64> > > >, std::__1::hash<unsigned long long>, std::__1::equal_to<unsigned long long> > >::emplace_unique<unsigned long long &, VarIntVector<unsigned long long,
      boost::container::scoped_allocator_adaptor<boost::interprocess::node_allocator<unsigned char, boost::interprocess::segment_manager<char,
      boost::interprocess::rbtree_best_fit<boost::interprocess::mutex_family, boost::interprocess::offset_ptr<void, long, unsigned long, 0>, 0>, iset_index>, 64> > >, VarIntVector<unsigned long
      long, boost::container::scoped_allocator_adaptor<boost::interprocess::node_allocator<unsigned char, boost::interprocess::segment_manager<char,
      boost::interprocess::rbtree_best_fit<boost::interprocess::mutex_family, boost::interprocess::offset_ptr<void, long, unsigned long, 0>, 0>, iset_index>, 64> > > >' requested here
        return table_.emplace_unique(
                      ^
/Users/richard/Code/C++/tilemaker/include/osm_store.h:443:30: note: in instantiation of function template specialization 'boost::unordered::unordered_map<unsigned long long,
      std::__1::pair<VarIntVector<unsigned long long, boost::container::scoped_allocator_adaptor<boost::interprocess::node_allocator<unsigned char, boost::interprocess::segment_manager<char,
      boost::interprocess::rbtree_best_fit<boost::interprocess::mutex_family, boost::interprocess::offset_ptr<void, long, unsigned long, 0>, 0>, iset_index>, 64> > >, VarIntVector<unsigned long
      long, boost::container::scoped_allocator_adaptor<boost::interprocess::node_allocator<unsigned char, boost::interprocess::segment_manager<char,
      boost::interprocess::rbtree_best_fit<boost::interprocess::mutex_family, boost::interprocess::offset_ptr<void, long, unsigned long, 0>, 0>, iset_index>, 64> > > >, std::__1::hash<unsigned
      long long>, std::__1::equal_to<unsigned long long>, boost::container::scoped_allocator_adaptor<boost::interprocess::node_allocator<std::__1::pair<unsigned long long,
      std::__1::pair<VarIntVector<unsigned long long, boost::container::scoped_allocator_adaptor<boost::interprocess::node_allocator<unsigned char, boost::interprocess::segment_manager<char,
      boost::interprocess::rbtree_best_fit<boost::interprocess::mutex_family, boost::interprocess::offset_ptr<void, long, unsigned long, 0>, 0>, iset_index>, 64> > >, VarIntVector<unsigned long
      long, boost::container::scoped_allocator_adaptor<boost::interprocess::node_allocator<unsigned char, boost::interprocess::segment_manager<char,
      boost::interprocess::rbtree_best_fit<boost::interprocess::mutex_family, boost::interprocess::offset_ptr<void, long, unsigned long, 0>, 0>, iset_index>, 64> > > > >,
      boost::interprocess::segment_manager<char, boost::interprocess::rbtree_best_fit<boost::interprocess::mutex_family, boost::interprocess::offset_ptr<void, long, unsigned long, 0>, 0>,
      iset_index>, 64> > >::emplace<unsigned long long &, VarIntVector<unsigned long long, boost::container::scoped_allocator_adaptor<boost::interprocess::node_allocator<unsigned char,
      boost::interprocess::segment_manager<char, boost::interprocess::rbtree_best_fit<boost::interprocess::mutex_family, boost::interprocess::offset_ptr<void, long, unsigned long, 0>, 0>,
      iset_index>, 64> > >, VarIntVector<unsigned long long, boost::container::scoped_allocator_adaptor<boost::interprocess::node_allocator<unsigned char,
      boost::interprocess::segment_manager<char, boost::interprocess::rbtree_best_fit<boost::interprocess::mutex_family, boost::interprocess::offset_ptr<void, long, unsigned long, 0>, 0>,
      iset_index>, 64> > > >' requested here
                auto result = mOutInLists->emplace(i,
                                           ^
/Users/richard/Code/C++/tilemaker/include/osm_store.h:712:37: note: in instantiation of function template specialization 'RelationStore::insert_front<std::__1::__wrap_iter<const unsigned long
      long *> >' requested here
                        auto const &relation = relations.insert_front(i, outerWayVec.begin(), outerWayVec.end(), innerWayVec.begin(), innerWayVec.end());
                                                         ^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/utility:503:5: note: candidate template ignored: could not match 'tuple' against 'VarIntVector'
    pair(piecewise_construct_t __pc,
    ^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/utility:401:5: note: candidate constructor template not viable: requires 0 arguments, but 3 were provided
    pair() _NOEXCEPT_(is_nothrow_default_constructible<first_type>::value &&
    ^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/utility:409:5: note: candidate constructor template not viable: requires 0 arguments, but 3 were provided
    pair() _NOEXCEPT_(is_nothrow_default_constructible<first_type>::value &&
    ^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/utility:417:14: note: candidate constructor template not viable: requires 2 arguments, but 3 were provided
    explicit pair(_T1 const& __t1, _T2 const& __t2)
             ^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/utility:426:5: note: candidate constructor template not viable: requires 2 arguments, but 3 were provided
    pair(_T1 const& __t1, _T2 const& __t2)
    ^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/utility:435:14: note: candidate constructor template not viable: requires 2 arguments, but 3 were provided
    explicit pair(_U1&& __u1, _U2&& __u2)
             ^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/utility:444:5: note: candidate constructor template not viable: requires 2 arguments, but 3 were provided
    pair(_U1&& __u1, _U2&& __u2)
    ^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/utility:453:14: note: candidate constructor template not viable: requires single argument '__p', but 3 arguments were provided
    explicit pair(pair<_U1, _U2> const& __p)
             ^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/utility:462:5: note: candidate constructor template not viable: requires single argument '__p', but 3 arguments were provided
    pair(pair<_U1, _U2> const& __p)
    ^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/utility:471:14: note: candidate constructor template not viable: requires single argument '__p', but 3 arguments were provided
    explicit pair(pair<_U1, _U2>&&__p)
             ^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/utility:480:5: note: candidate constructor template not viable: requires single argument '__p', but 3 arguments were provided
    pair(pair<_U1, _U2>&& __p)
    ^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/utility:489:14: note: candidate constructor template not viable: requires single argument '__p', but 3 arguments were provided
    explicit pair(_Tuple&& __p)
             ^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/utility:497:5: note: candidate constructor template not viable: requires single argument '__p', but 3 arguments were provided
    pair(_Tuple&& __p)
    ^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/utility:562:9: note: candidate constructor template not viable: requires 5 arguments, but 3 were provided
        pair(piecewise_construct_t,
        ^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/utility:309:5: note: candidate constructor not viable: requires 1 argument, but 3 were provided
    pair(pair const&) = default;
    ^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/utility:310:5: note: candidate constructor not viable: requires 1 argument, but 3 were provided
    pair(pair&&) = default;
    ^
1 error generated.
make[2]: *** [CMakeFiles/tilemaker.dir/src/osm_lua_processing.cpp.o] Error 1
make[1]: *** [CMakeFiles/tilemaker.dir/all] Error 2
make: *** [all] Error 2
````

</summary>

**Comment by kleunen** [comment]
Yes, and I also noticed that it was throwing a bad_alloc exception. Indeed getting it to work on all platforms is quite tricky. 

So, let me see if I can fix this.

**Comment by kleunen** [comment]
I also noticed lua 5.4 was actually faster than 5.3. So when it builds again, you may want to try the build from the CI.

**Comment by kleunen** [comment]
It is building again, so should work on your machine also :)

**Comment by systemed** [comment]
It does!

**Comment by kleunen** [comment]
I am not sure if it is stable though. I still see some issues. I had to change some stuff to get it to compile on MacOS, but I think this is giving problems now. Have a try.

**Comment by kleunen** [comment]
It is stable and compiling now

**Comment by kleunen** [comment]
At a certain point I was pretty certain it was never going to work. But there is always this one little thing you are not looking at, and once you know, the solution is easy. 

If you can add the boundaries to the generation of the map and improve the lower zoom level rendering a bit. ( I changed the config the include the main roads and waterways in zoomlevel >= 6). I would be very grateful

**Comment by systemed** [comment]
I'll run a quick test run later and then merge this - thank you!

I'll then have a look at the stylesheet/config today or tomorrow.

**Comment by kleunen** [comment]
I would be very grateful, thank you very much. I think I have done enough for this project for now :) Maybe in the future i will have a look into speeding up the loading or something. But for now, maybe I have spend a bit too much hours :D

You know how to get the precompiled binaries from the CI ? I think it is useful for people if you put precompiled binaries on the github. Especially on windows, people might not want to compile themselves. 

And I made small tutorial on my new blog :)
https://blog.kleunen.nl/blog/tilemaker-generate-map

**Comment by systemed** [comment]
>  I think I have done enough for this project for now :) 

Definitely, and thank you!

I've tested it successfully on macOS 10.14 and 11.0 and it builds and runs fine on both. I'll run a bigger Ubuntu test later.

> You know how to get the precompiled binaries from the CI ?

I don't - I can google it but if you have any suggestions...

**Comment by kleunen** [comment]
Click here in the discussion on 'Show all checks', in the 'All checks have passed' box. Click on details, and on the right you can see 'Artifacts'. There you can download all the builds for windows/linux/macos. When you make a release, you can add them to the release. 

image

**Comment by systemed** [comment]
Builds and runs perfectly on Ubuntu too - thank you!

I'll do a release (with binaries) once I've sorted out #196 and #200.

**Pull request merged**
